name: semantic-release
on:
  push:
    branches:
      - main

jobs:
  test:
    name: test sr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: codfish/semantic-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}